---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    # filter.fluxcd.io/chart-image: semver:~0.
    # filter.fluxcd.io/vscode: "regex:^2.[0-9]+-.*$"
spec:
  releaseName: traefik-forward-auth
  rollback:
    enable: true
  chart:
    git: https://github.com/kelvl/helm-charts
    ref: master
    path: charts/traefik-forward-auth
  values:
    nodeSelector: 
      kubernetes.io/hostname: nas-master
    config:
      domain: ["*"]
      insecureCookie: "false"
      providers:
        google:
          enabled: true
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: default
        traefik.ingress.kubernetes.io/router.middlewares: default-traefik-forward-auth@kubernetescrd
  valueFileSecrets:
  - name: "traefik-forward-auth-helm-values"
