---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    filter.fluxcd.io/chart-image: semver:~0
    repository.fluxcd.io/vscode: vscode.repository
    tag.fluxcd.io/vscode: vscode.tag
    filter.fluxcd.io/vscode: semver:~3
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/app: semver:~0.114
spec:
  releaseName: home-assistant
  rollback:
    enable: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: home-assistant
    version: 0.13.2
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.116.4
    persistence:
      enabled: true
      existingClaim: home-assistant
    nodeSelector:
      kubernetes.io/hostname: nas-master
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        ingress.kubernetes.io/ssl-redirect: "true"
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    hostNetwork: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    # podAnnotations:
    #   backup.velero.io/backup-volumes: config
    vscode:
      image:
        repository: codercom/code-server
        tag: 3.6.0
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          ingress.kubernetes.io/ssl-redirect: "true"
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: default-traefik-forward-auth@kubernetescrd
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 35m
        memory: 2000Mi
    monitoring:
      enabled: false
  valueFileSecrets:
  - name: "home-assistant-helm-values"
