git:
  url: "git@github.com:kelvl/k3s-gitops"
  branch: master
  path: deployments
registry:
  rps: 1
  burst: 1
nodeSelector:
  kubernetes.io/hostname: nas-master
memcached:
  nodeSelector:
    kubernetes.io/hostname: nas-master
# memcached:
#   tolerations:
#   - key: "arm"
#     operator: "Exists"
additionalArgs:
  - --connect=ws://fluxcloud
# prometheus:
#   enabled: true
#   serviceMonitor:
#     create: false
#     interval: 30s
#     scrapeTimeout: 10s
#     namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
