apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCZLOuFXPRGHb9oEdoNm+bTYj02beoPSobFqzWclguRtSypyGK40cL6vZzhyV4cnpITsFC53Wp0XTZgfyr4jmoCp7/+wf9WBTieFR9XK7MdJKe5ErAgxJfWFUgVVhDA6uzlkwpv+QbbOgZYCdrCIRmOQBJ7BAoG4D3Vt6J7L/LURARnC2nc2C+BsJNv02jgu+dbwSnL73PhlLG6ZNnUXILpys/3s2jTgm6antWC1or5mJssbpo4SXD30Z9CQXiEqR6RxRbRZqBi4gS0vGPDwImGgnrKfYNh886HkaHuF4NF4ftf4FsSEE/GTGgmm9st0zmp+cGNRY1sVLzmXzY9nLNUQZ+Ub2mrKWq1aoqSAC0YFsQw7njh/gPykx2lvGakp7UeaRTwdU0ZEmwuRK63QxdSpp8Wd5Vx+elutGGuzJNjImspDzW2P1llrwNTdoITPWFhrLrNoWXuwBtBQCktM6Mz0yagDPYwpfNNBgZNUgG30W1KU1yen48xzmj7vXDNdy7fpQEl3x4W73ssw+4hQR495S464fSLpe6g/GoP6eS7WWWFgPZ1lxboDGcb+llbPJMkVcm0dXdINb7P8YE0xZfUdD8eryiJDe+J7R9MafinlIDk1WGJoZEpTSIRb5OMO+52RCX39IzZbsx6Rp8cb+Avd3T75GWhXQZLttDhhIHfwSELmArNBbiwtl/j0qD81W0RoveSDkhVPabNMraOZvn4LyWX3v4zDqZcRx52N4a780TxlsFlxWtzup4r
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default
status: {}

