apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBi4+o3kso9hBz8u/0bTBiZvDj5W/ltVtDj+b3yeUpqvm6K+NKZqhAE7T3Xabzjlyz3hAIPJdFEZhMCkPrr91vw8jrQ55Dh9du/RukLML58nuhD1us814SsmNiZaUgmNDpnplYk3jteVMBI68WIB/c8FZ5l8Q0ZkBuqtcNP3id3PCeb790IVxXn0l7FjaA18NogF+o+C/nRMs94o9+tiORn16AiAUa5b90DE7BCNTaRw6do4iViQvGeBpVEzW1uudP4Cy5Lak+pMeTpDDVlaTc86fdkKRcKPgrjYzKFtBoycH3KOXr2ta1hGEw5YyP05z2Bt3//gqBkXUQBLOXbCpipDKpwaHD7od1DFHyx+y3pYPvtuCyTjEYChFo5URmxOLWedgKX6kswb3LRfCn7eDDax54Gkrf32oUS8scOywxWnBRVdKdRselfm9wb/EjBq2vBfy3MT3KSSN2REv0U78y4XXjKK0A1fescN5xv6dDC5C3ZM7QAp0mw5plz9wNWB8B/Ig4gqlLLun2GTkuuJqZJRBBku+NyeK9PXgnbR0tCXC//3ewOCI+VgUP3Rnvb5J3dcakY6rof6urkithbswqNyuy/gUz/78DUWwcDsAQdb4Ftl6NstoAXG9wN3Ulk+0RsdAFzc8HqQCQx3J+CRH1z1x9y9lUHqgqutsI92LQfFy2i7pbyZtmfUTGu7ZgWdCZOyANaUe6ETGR0rvG8/OxMiwxIf3q+daEqA1KzYbxVWDKEh5TCXWPII14K
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default
status: {}

