apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCiQDolVNfEKq6vsw+uY3AdgBX5m2iK6TBMCTZb2pg0G0C+WWt6Rqz5TtF38HVzfW7zT9dDj/e+hPT3flOaj7ZAdLicZL0FfHjLp04o1N0fs8qUcZdb63MSdtxl7+pygHfOHMr37B6zPt42QRZmpReCMgsLXHzywaD4XlapcjFMQIfmLm44gsLNCN2yHz2tVO5nbFhCvJP0/vpYLbACKAMvlSF52YQ3IHEYv1rXa/8a+5gFYGTsMU4HYnehCttOp589XLtOkInIdRC0lFU5A4lXK1s7k9eKXzB3fbKe/lNAlAlohFNjYW3jnuOUAgKWjFF16hbpMz8RO/ZNFAt3nkQp43dENU6EYAK2lrPFyoJ6r6r5JlAc+8LKssAW+l1D+kg5coGYm1AyQz35ZysSef9GfEt7H8FkG9ZvlhPgdFDErbeeTHoz5geeaZNA1Qcg1Bn3YeVl47un4mETEnAFcHszGKbDtA2SCUay0sWbut1cduBTtdfdFN3CCDZn3hswm/M9zERK8mG8jjNnsX+/96CotOQb4lODga6RJ4y1BPK98OkOICRjbOl5Kh6Stg3ZjqDH72gdxfn8tE2eyJRUz02jozIuHd+FmfKfLQ4bWvRKobKW3IpCC4egcKpae6Cz+e7TGiIbNfSo53r2cpg7CAQ4AQdGiUUDubLxLFOilbZCOx3OlBecCiDOqfxtRLPu7o13e/xSM4bKUPvAWngaRDfjYPmO0SC11eyz0sGLz28UAt/YMxoZ8cGPrrqt
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default
status: {}

