---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    repository.fluxcd.io/app: image.name
    tag.fluxcd.io/app: image.tag
    filter.fluxcd.io/app: 'glob:v0.*'
spec:
  releaseName: jackett
  rollback:
    enable: false
  chart:
    repository: https://billimek.com/billimek-charts/
    name: jackett
    version: 2.3.0
  values:
    nodeSelector: 
      kubernetes.io/hostname: nas-master
    probes:
      startup:
        initialDelaySeconds: 120
      liveness:
        periodSeconds: 60
      rediness:
        periodSeconds: 60
    image:
      name: linuxserver/jackett
      tag: v0.16.127-ls63
    puid: 1000
    pgid: 1000
    timezone: "Etc/GMT-8"
    persistence:
      config:
        enabled: true
        existingClaim: jackett
      torrentblackhole:
        enabled: true
        existingClaim: downloads
        subPath: watch
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: "default"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: default-traefik-forward-auth@kubernetescrd
      path: /
  valueFileSecrets:
    - name: "jackett-helm-values"
