---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/mountpoints/app-data/kubernetes/jackett
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nas-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: jackett
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi