git:
  url: "git@github.com:kelvl/k3s-gitops"
registry:
  rps: 1
  burst: 1
# memcached:
#   tolerations:
#   - key: "arm"
#     operator: "Exists"
# additionalArgs:
# - --connect=ws://fluxcloud
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
