apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCAxl23Ga8ICRHkb0XT1MyBvKdw6EV8L74lqEENVNNJQ2INRMwwoHie1jpLq4pOUGPM2gaOcX4RdmM6RniLzr4+1ik8OY7h+DoiQOOOdwNbglgeX5ZUtHgDZlLflocpuetuIU3mN8Za1Svsi2MUdE61Dk+ZgnTzezt8TVIduQryLyvhz09o/0MtBTd9Pw0mC1pyfx5+qTbaHxBLlUxi5o/ThhCkccjnUSLDxGnf7FjP8KC7Msjp9/QmysCYsV9rq75YI7NlA8hWRJx79WZi12Nt8CM6W8XYmPHTsf4Qd3HZwoEV23rE8+tLbSXThB93D0f0UcvkoPAq+oVJjEb+B7T7iY2w4vITBf9Hz4fle7sLkFHzbxe+lU9d509beeEMOUkLOjlA2/WASz8il9LmqVSxn90QSRnD+PS5f0vENw7WvTHkWgDvCFetMR7GsJag5rHd/YjiSEoUbV83Ou+3TgI+4gTP23YJUWcK1aJRmt0EDn2coaUTFGe0dr7RKzpVbR821R/Bw+kZdvhXwoc7M7sx1cN5uuDkTdC7Od0RptwOIBOGg6rkj5NturYKgx8Gc940M2f5a21QQt1ylFDWK6cnl43mzRp/C14itMgc9RgyUSevAEiKSmEO45FAYtSpxQ1PBHNKNQr+Xq/vdWn37Ss5Yi3F8eQnE/VRqMG4j76phZKTDzEpfEmJoJ4xHPU5rx94wTC1clH++pHmR/3l1GOsbD1O9CKb5iswq7+yS1Bhw4Pf8l/rJ/ro0rOF
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

