apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBZBPGMnUJtmUNTI2OemYCOlQJpiMmgMaPmwr6LUlbivXycvTJDp/FEikt0EFYxzzr28CIrjlSH2ofW3kjQkhFMenmKoY/K6MA1iDRwSjNZBT3rVS07T3jjUvaYm/+4ElTYctIMtYHaiTP66x6kxgZ1x7d/w/4DEXYIj8q7am86usxsBJ/4K7nVoT2Ey0Mq95484BvcW1eydehavDHSuNaw87d8EO42DXb4WGr3QKBpaUin8dl7RtTS2Mb1WRrzzfqa47MATZTMgfcxxuIvVygj2qnRMAKQy4zmemzeqEEDz4qM0bMtp5KfnDo+Vij5Lf1p20uptTMZ5tHovcFbvgRoggkwuv0D36ev3BJUTJY+5xbLfYzfXkNZE80eL/+MLj6E70Gu7frRO8FS4z6/UZnqUALo9m6nmBgNe3lYhFMDsmxJl6tKU8kvGhMWqfod3EPXGFFGM5HKYgRaji+uLSqlbK5pFyJU71PCNi7QH5pq2Afg5QQ38cqDOW+/liXjAYv0UF59zPfX6ZluJU2y2CWKAPWHJ5UkVwLskEw4dODJaRT6od6gub06xwiiq5Y7kaWF4bvL1ku4ty2j/uBB9+WzvbBcKW/0PidJdWuX3WymmWy+xgpCGiyz/BUT1WMnojSsZInVvlTG4a07SnLJ3J1vYV5fT/anRZWD0sZrpnvYyX1/BKzLq1PbHjxHsLYQrQG3Z2ov+Er4PF7eiJ8EVYq+p979FS8oeS8Ce5aKmHOkZGwbWoSvBfYoizPU
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

