apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAyhagpRxhjfPe8T7A2goJO6UHGPOJ6YdkGKPxAdrjQf4VdVxwXbPL61bjvFRt1vx0d2IqPzT0o3/XBRIzt9gdAAA4bWSZawWYkAKs5ty1gicf5FJ3NMZ9HgAW8XmHuGQe96L1BQj5rvrjMdsh10xIyN55fMR3MGYda4ygqnqSWN6l6CZhZlxtjxHzQMmZU/D1DBC0of+oYrAlxGFa2rZoF8O4w/7SNjiyTM3ZpAR4IyaAFHVuDLoqfSHMQ+1nAAdolkHiqljMG4/qzNzMYSd97WNXaQDkyTLT+HEeijKxTJWepThumlJSh+vzdPD7DiYHZBpWwg8q4aw19A5+k2K3Hn+RmAuKxCNaWKJpVswpNFLQX8V/km1tLltEB+d0HXFEvntRcFRaHx4uYUwH9xlKTi6OmHV+jXdoJKUDKjpodGzgrK+7SxvXprffeJm3/yw8eiW1Yd0ZVJJcaw4CLdeeaail0xEpY6eb/cM7v7KXCd3uEIfh7SUvCov9UXgbt7CMMWb0L4jEQls+updq76HaLJuQHC+GWeHcmqMIstIZHv/pJ8al7mZfnR6G5Krcy1cPCOSfvtqVvcc1EVwUcnWKPDmn/bxVcnno1AxgSo82Nh2ZfOMZmn4tMQXjJIz4zitsTs3deT76W1j1irBuTxLQPBHVyMvbUjk2i6b3gFbMOFeBVchA7hyIwcHEPRLu1uNOd0fAHqGF34QqyqUW75MbOQxidcLt4Mf+reXI/Fm5nJJLqTngXTKZJUEVE
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

