apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCsAs2kpRa33pon0mSTH5Xl2e1H8jGu0z8STdyUfHfZPuasQUPFWYnmTtuRWM4fbX+x6pc36XXmLULI4KRAbwGjBAuFHIcz0m2jtG056GlDUgWCcCBpySy42zBkTCc/eDo+4CRlYc7Yn/kHtyYmAJkjV2sxC6PXVn18+y5uqP5A81QPM/bplNlQjDmETBm97N0ONWF8d0e6WMKNRLNJif8hUAa6ZAnQO0je0CFGN/bS5hA+PR016FlY+9bEFOeVKQiIW30Upy9Quscr0xkES51feOzd9bv3/GXiFopr65yB1XeTPPvr2n+CWifFRGbBealOlKNRCneZ8ixRZ3hVGcYT9H4F45ty/qxHRo1pxViF9NaYTRLEYLvvAc9fZH8lkpTQuEruHNKBShytKRmVghnHtuBmHxaWs6Z/P+Mupo2Z46ee4XSkysmUhKwxPqoxNTE9crzMO4yrUCek5/A8NLOleiEZHSsFSLalmwgZtzrm7r5v14ksFC5JVPVTGl+YvsTRZEALTyS/v/OTAp4JuAtdqVk2P+fPywKiPNq7/x+LqLt7/0MgW8jdF8KKVscTS9qet2Cu0GuWO1Uw2310ZV2W1E/rwJ9hN6hSwfWe69zgfc3SYDMkQT4vtATGsIs66uznqHJLC39pHfj7R3RUOKiMsGdQBc2DTa1C8A3cFQnGrrQZpN3EiktBehQmckFxWxw4iyM4LbVUAd+bqItz1su9Qy00bOktDKk1l8mPYSbRxVXfPm/jkYJzAicQ
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default
status: {}

