---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  helmVersion: v3
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 1.0.1
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/kelvl/k3s-gitops/master/deployments/flux/helm-operator/helm-operator-values.yaml