# createCRD: true
nodeSelector:
  kubernetes.io/hostname: nas-master
git:
  ssh:
    secretName: flux-git-deploy
chartsSyncInterval: "15m"
statusUpdateInterval: "15m"
helm: 
  versions: v3
# prometheus:
#   enabled: true
#   serviceMonitor:
#     create: false
#     interval: 30s
#     scrapeTimeout: 10s
#     namespace: flux
